name: Load Test
description: Use Artillery.io to perform pre-defined load tests from the selected package
inputs:
  package:
    description: 'The package you wish to run your load tests against'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make reports directory
      shell: bash
      run: mkdir reports

    - name: Execute load tests
      uses: docker://artilleryio/artillery:latest
      with:
        entrypoint: /home/node/artillery/bin/run
        args: run --output ./reports/${{ inputs.package }}-report.json ./packages/${{ inputs.package }}/loadtest/websockets.yml

    - name: Generate HTML report
      uses: docker://artilleryio/artillery:latest
      with:
        entrypoint: /home/node/artillery/bin/run
        args: report --output ./reports/${{ inputs.package }}.html ./reports/${{ inputs.package }}-report.json

    - name: Archive test report
      uses: actions/upload-artifact@v2
      with:
        name: artillery-test-report
        path: reports/*
