name: Load Test
description: Use Artillery.io to perform pre-defined load tests from the selected package
inputs:
  package:
    description: 'The package you wish to run your load tests against'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Copy test files
      uses: Bhacaz/checkout-files@v2
      with:
        files: packages/${{ inputs.package }}/loadtest

    - name: Execute load tests
      id: execute-load-tests
      shell: bash
      run: /home/node/artillery/bin/artillery run packages/${{ inputs.package }}/loadtest/*.yml

    # - name: Execute load tests
    #   id: execute-load-tests
    #   shell: bash
    #   run: /home/node/artillery/bin/artillery run --output ${{ inputs.package }}-report.json packages/${{ inputs.package }}/loadtest/*.yml

    # - name: Generate HTML report
    #   id: generate-html-report
    #   shell: bash
    #   run: /home/node/artillery/bin/artillery report --output ${{ inputs.package }}-report.html ${{ inputs.package }}-report.json

    # - name: Archive test report
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: artillery-test-report
    #     path: ${{ inputs.package }}-report.json
