name: Load Test
description: Use Artillery.io to perform pre-defined load tests from the selected package
inputs:
  package:
    description: 'The package you wish to run your load tests against'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Copy test files
      uses: Bhacaz/checkout-files@v2
      with:
        files: packages/${{ inputs.package }}/loadtest

    - name: Make reports directory
      shell: bash
      run: mkdir reports

    - name: Execute load tests
      shell: bash
      run: /home/node/artillery/bin/run run --output reports/${{ inputs.package }}-report.json packages/${{ inputs.package }}/loadtest/*

    - name: Generate HTML report
      shell: bash
      run: /home/node/artillery/bin/run report --output reports/${{ inputs.package }}.html reports/${{ inputs.package }}-report.json

    - name: Archive test report
      uses: actions/upload-artifact@v2
      with:
        name: artillery-test-report
        path: reports/*
