name: Load Test
description: Use Artillery.io to perform pre-defined load tests from the selected package
inputs:
  package:
    description: 'The package you wish to run your load tests against'
    required: true
    default: ''
  custom-run:
    description: 'Your custom artillery run command to be passed when package is set to custom'
    required: false
    default: ''
  custom-report:
    description: 'Your custom artillery report command to be passed when package is set to custom'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make reports directory
      shell: bash
      run: mkdir reports

    - name: Execute load tests
      if: ${{ inputs.package != 'custom' }}
      uses: docker://artilleryio/artillery:latest
      with:
        entrypoint: /home/node/artillery/bin/run
        args: run --output ./reports/${{ inputs.package }}-report.json ./packages/${{ inputs.package }}/loadtest/websockets.yml

    - name: Generate HTML report
      if: ${{ inputs.package != 'custom' }}
      uses: docker://artilleryio/artillery:latest
      with:
        entrypoint: /home/node/artillery/bin/run
        args: report --output ./reports/${{ inputs.package }}.html ./reports/${{ inputs.package }}-report.json

    - name: Execute custom load tests
      if: ${{ inputs.package == 'custom' && inputs.custom-run != '' }}
      uses: docker://artilleryio/artillery:latest
      with:
        entrypoint: /home/node/artillery/bin/run
        args: ${{ inputs.custom-run }}

    - name: Generate Custom HTML report
      if: ${{ inputs.package == 'custom' && inputs.custom-report != '' }}
      uses: docker://artilleryio/artillery:latest
      with:
        entrypoint: /home/node/artillery/bin/run
        args: ${{ inputs.custom-report }}

    - name: Archive test report
      uses: actions/upload-artifact@v2
      with:
        name: artillery-test-report
        path: reports/*
