# name: Artillery Socket.IO Load Test

# on:
#   workflow_dispatch:

# jobs:
#   load-test:
#     runs-on: ubuntu-latest

#     container: artilleryio/artillery

#     steps:
#       - name: Copy test files
#         uses: Bhacaz/checkout-files@v2
#         with:
#           files: packages/${{ inputs.package }}/loadtest

#       - name: Make reports directory
#         run: mkdir reports

#       - name: Execute load tests
#         run: /home/node/artillery/bin/run run --output reports/${{ inputs.package }}-report.json packages/${{ inputs.package }}/loadtest/*

#       - name: Generate HTML report
#         run: /home/node/artillery/bin/run report --output reports/${{ inputs.package }}.html reports/${{ inputs.package }}-report.json

#       - name: Archive test report
#         uses: actions/upload-artifact@v2
#         with:
#           name: artillery-test-report
#           path: reports/*

name: Perform Load Tests

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: What package do you want to run load tests against
        required: true
        options:
          - main

jobs:
  perform-load-tests:
    name: Perform Load Tests
    runs-on: ubuntu-latest
    container: artilleryio/artillery
    steps:
      - uses: actions/checkout@v3
      - id: perform-load-test
        uses: ./.github/actions/load-test
        with:
          package: ${{ inputs.package }}
