name: Artillery Socket.IO Load Test

on:
  workflow_dispatch:

jobs:
  artillery:
    runs-on: ubuntu-latest

    container: artilleryio/artillery

    steps:
      - name: Checkout repository
        id: clone-repo
        uses: actions/checkout@v2

      - name: Execute load tests
        id: execute-load-tests
        run: /home/node/artillery/bin/artillery run loadtest/websockets.yml
