name: Artillery Socket.IO Load Test

on:
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest

    container: artilleryio/artillery

    steps:
      - name: Checkout repository
        id: clone-repo
        uses: actions/checkout@v2

      - name: Make reports directory
        run: mkdir reports

      - name: Execute load tests
        run: /home/node/artillery/bin/run run --output reports/report.json loadtest/*

      - name: Generate HTML report
        run: /home/node/artillery/bin/run report --output reports/report reports/report.json

      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: artillery-test-report
          path: reports/*
